name: Release Container binary
run-name: Release Container binary Version ${{ github.event.release.tag_name }}

on:
  release:
    types: [created]
  
jobs:
  release:
    name: release ${{ github.event.release.tag_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: true
            override: true

      - name: Build
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --bin container --target x86_64-unknown-linux-musl
          mv target/x86_64-unknown-linux-musl/release/container target/release/container_x86_64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/container_x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: "Publish"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./feature/src/"
          oci-registry: "ghcr.io"
          generate-docs: "true"
          features-namespace: "MunsMan/autoForward"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
